name: parkways
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.1
  firebase_auth: any
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.4.0
  introduction_screen: ^3.1.9
  onboarding: ^3.1.0
  provider: ^6.0.5
  logging: ^1.2.0
  fluttertoast: ^8.2.2
  firebase_database: ^10.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700